/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashAlert: typeof import('./src/components/alerts/DashAlert.vue')['default']
    DashButton: typeof import('./src/components/buttons/DashButton.vue')['default']
    DashCheckbox: typeof import('./src/components/checkboxes/DashCheckbox.vue')['default']
    DashContainer: typeof import('./src/components/containers/DashContainer.vue')['default']
    DashDatePicker: typeof import('./src/components/selects/DashDatePicker.vue')['default']
    DashDateRangePicker: typeof import('./src/components/selects/DashDateRangePicker.vue')['default']
    DashDotDrowpdown: typeof import('./src/components/dropdowns/DashDotDrowpdown.vue')['default']
    DashDropwdown: typeof import('./src/components/dropdowns/DashDropwdown.vue')['default']
    DashDropwDown: typeof import('./src/components/dropdowns/DashDropwDown.vue')['default']
    DashFormGenerator: typeof import('./src/components/forms/DashFormGenerator.vue')['default']
    DashGrid: typeof import('./src/components/grids/DashGrid.vue')['default']
    DashImage: typeof import('./src/components/image/DashImage.vue')['default']
    DashInput: typeof import('./src/components/inputs/DashInput.vue')['default']
    DashLayoutImage: typeof import('./src/components/image/DashLayoutImage.vue')['default']
    DashModal: typeof import('./src/components/modal/DashModal.vue')['default']
    DashPanel: typeof import('./src/components/grids/DashPanel.vue')['default']
    DashPopover: typeof import('./src/components/popover/DashPopover.vue')['default']
    DashProgressBar: typeof import('./src/components/progressBar/DashProgressBar.vue')['default']
    DashRibbon: typeof import('./src/components/ribbon/DashRibbon.vue')['default']
    DashSelect: typeof import('./src/components/selects/DashSelect.vue')['default']
    DashSlider: typeof import('./src/components/image/DashSlider.vue')['default']
    DashSwitch: typeof import('./src/components/checkboxes/DashSwitch.vue')['default']
    DashTab: typeof import('./src/components/tabs/DashTab.vue')['default']
    DashTabs: typeof import('./src/components/tabs/DashTabs.vue')['default']
    DashTagsInput: typeof import('./src/components/inputs/DashTagsInput.vue')['default']
    DashToast: typeof import('./src/components/toast/DashToast.vue')['default']
    DashTooltip: typeof import('./src/components/tooltip/DashTooltip.vue')['default']
    DashTypeWritter: typeof import('./src/components/typography/DashTypeWritter.vue')['default']
    DashTypography: typeof import('./src/components/typography/DashTypography.vue')['default']
    FormButton: typeof import('./src/components/buttons/FormButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LateraItem: typeof import('./src/components/navs/lateral/LateraItem.vue')['default']
    LateralItemToggle: typeof import('./src/components/navs/lateral/LateralItemToggle.vue')['default']
    LateralNavbar: typeof import('./src/components/navs/lateral/LateralNavbar.vue')['default']
    LoadingOverlay: typeof import('./src/components/overlay/LoadingOverlay.vue')['default']
    Overlay: typeof import('./src/components/overlay/Overlay.vue')['default']
    RippleButton: typeof import('./src/components/buttons/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCard: typeof import('./src/components/cards/SimpleCard.vue')['default']
    SuperiorNavbar: typeof import('./src/components/navs/superior/SuperiorNavbar.vue')['default']
    TabsContent: typeof import('radix-vue')['TabsContent']
    TabsTrigger: typeof import('radix-vue')['TabsTrigger']
    ToastContainer: typeof import('./src/components/toast/ToastContainer.vue')['default']
  }
}
