/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashCheckbox: typeof import('./src/components/checkboxes/DashCheckbox.vue')['default']
    DashContainer: typeof import('./src/components/containers/DashContainer.vue')['default']
    DashDatePicker: typeof import('./src/components/selects/DashDatePicker.vue')['default']
    DashDateRangePicker: typeof import('./src/components/selects/DashDateRangePicker.vue')['default']
    DashDotDrowpdown: typeof import('./src/components/dropdowns/DashDotDrowpdown.vue')['default']
    DashDropwdown: typeof import('./src/components/dropdowns/DashDropwdown.vue')['default']
    DashDropwDown: typeof import('./src/components/dropdowns/DashDropwDown.vue')['default']
    DashFormGenerator: typeof import('./src/components/forms/DashFormGenerator.vue')['default']
    DashGrid: typeof import('./src/components/grids/DashGrid.vue')['default']
    DashInput: typeof import('./src/components/inputs/DashInput.vue')['default']
    DashPanel: typeof import('./src/components/grids/DashPanel.vue')['default']
    DashSelect: typeof import('./src/components/selects/DashSelect.vue')['default']
    DashSwitch: typeof import('./src/components/checkboxes/DashSwitch.vue')['default']
    DashTagsInput: typeof import('./src/components/inputs/DashTagsInput.vue')['default']
    FormButton: typeof import('./src/components/buttons/FormButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LateraItem: typeof import('./src/components/navs/lateral/LateraItem.vue')['default']
    LateralItemToggle: typeof import('./src/components/navs/lateral/LateralItemToggle.vue')['default']
    LateralNavbar: typeof import('./src/components/navs/lateral/LateralNavbar.vue')['default']
    LoadingOverlay: typeof import('./src/components/overlay/LoadingOverlay.vue')['default']
    Overlay: typeof import('./src/components/overlay/Overlay.vue')['default']
    RippleButton: typeof import('./src/components/buttons/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCard: typeof import('./src/components/cards/SimpleCard.vue')['default']
    SuperiorNavbar: typeof import('./src/components/navs/superior/SuperiorNavbar.vue')['default']
  }
}
