/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashDotDrowpdown: typeof import('./src/components/dropdowns/DashDotDrowpdown.vue')['default']
    DashDropwdown: typeof import('./src/components/dropdowns/DashDropwdown.vue')['default']
    DashDropwDown: typeof import('./src/components/dropdowns/DashDropwDown.vue')['default']
    DashSelect: typeof import('./src/components/selects/DashSelect.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LateraItem: typeof import('./src/components/navs/lateral/LateraItem.vue')['default']
    LateralItemToggle: typeof import('./src/components/navs/lateral/LateralItemToggle.vue')['default']
    LateralNavbar: typeof import('./src/components/navs/lateral/LateralNavbar.vue')['default']
    RippleButton: typeof import('./src/components/buttons/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuperiorNavbar: typeof import('./src/components/navs/superior/SuperiorNavbar.vue')['default']
  }
}
